name: w_5
description: watch and weather for some cityes

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.1
  google_fonts: ^3.0.1
  provider: ^6.0.3
  sqflite: 
  path:
  http:
  intl: ^0.17.0
  weather_icons:
  geolocator: ^8.0.0
# flutter_launcher_icons: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/weather-app.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
